name: "\U0001F41E Bug report"
description: Create a report to help us improve
body:
  - type: checkboxes
    attributes:
      label: "Before you start, make sure to:"
      description: More than half issues of json-editor-vue turned out to be invalid or irrelevant.
      options:
      - label: Read the [doc](https://github.com/cloydlau/json-editor-vue/blob/main/README.md)
        required: true
      - label: Be aware that json-editor-vue is only a Vue wrapper for [svelte-jsoneditor](https://github.com/josdejong/svelte-jsoneditor)
        required: true
      - label: Have a try at the latest version
        required: true
      - label: Search to see if your issue already exists
        required: true
      - label: Look for / ask questions on [Stack Overflow](https://stackoverflow.com/questions/ask)
        required: false
  - type: input
    id: json-editor-vue_version
    attributes:
      label: json-editor-vue version
    validations:
      required: true
  - type: input
    id: vanilla-jsoneditor_version
    attributes:
      label: vanilla-jsoneditor version
    validations:
      required: true
  - type: input
    id: vue_version
    attributes:
      label: vue version
    validations:
      required: true
  - type: input
    id: vue-composition-api_version
    attributes:
      label: "@vue/composition-api version"
      placeholder: Only for Vue 2.6 or earlier
    validations:
      required: false
  - type: input
    id: nuxt_version
    attributes:
      label: nuxt version
    validations:
      required: false
  - type: input
    id: reproduction-link
    attributes:
      label: Link to minimal reproduction
      description: |
        The easiest way to provide a reproduction is by showing the bug in [The SFC Playground](https://sfc.vuejs.org/).
        If it cannot be reproduced in the playground and requires a proper build setup, try [StackBlitz](https://vite.new/vue).
        If neither of these are suitable, you can always provide a GitHub repository.

        The reproduction should be **minimal** - i.e. it should contain only the bare minimum amount of code needed
        to show the bug. See [Bug Reproduction Guidelines](https://github.com/cloydlau/json-editor-vue/blob/main/.github/bug-repro-guidelines.md) for more details.

        Please do not just fill in a random link. The issue will be closed if no valid reproduction is provided.
        [Why reproduction is required?](https://antfu.me/posts/why-reproductions-are-required)
      placeholder: Reproduction Link
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do after opening your repro in order to make the bug happen? Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected?
    validations:
      required: true
  - type: textarea
    id: actually-happening
    attributes:
      label: What is actually happening?
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages json-editor-vue,vanilla-jsoneditor,vue,@vue/composition-api,nuxt --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      description: e.g. some background/context of how you ran into this bug.
