name: "\U0001F680 New feature proposal"
description: Suggest an idea for this project
labels: [":sparkles: feature request"]
body:
  - type: checkboxes
    attributes:
      label: "Before you start, make sure to:"
      description: More than half issues of json-editor-vue turned out to be invalid or irrelevant.
      options:
      - label: Read the [doc](https://github.com/cloydlau/json-editor-vue/blob/main/README.md)
        required: true
      - label: Be aware that json-editor-vue is only a Vue wrapper for [svelte-jsoneditor](https://github.com/josdejong/svelte-jsoneditor)
        required: true
      - label: Have a try at the latest version
        required: true
      - label: Search to see if your issue already exists
        required: true
      - label: Look for / ask questions on [Stack Overflow](https://stackoverflow.com/questions/ask)
        required: false
  - type: textarea
    id: problem-description
    attributes:
      label: What problem does this feature solve?
      description: |
        Explain your use case, context, and rationale behind this feature request. More importantly, what is the **end user experience** you are trying to build that led to the need for this feature?
      placeholder: Problem description
    validations:
      required: true
  - type: textarea
    id: proposed-API
    attributes:
      label: What does the proposed API look like?
      description: |
        Describe how you propose to solve the problem and provide code samples of how the API would work once implemented. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your code blocks.
      placeholder: Steps to reproduce
    validations:
      required: true
