name: 'ci'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'

      - run: PUPPETEER_SKIP_DOWNLOAD=1 pnpm install

      - name: Run case police
        run: npx case-police --fix

      - name: Run eslint
        run: pnpm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'

      - run: PUPPETEER_SKIP_DOWNLOAD=1 pnpm install

      - name: Run unit tests
        run: pnpm run test-unit
